import { useRef, useState } from 'react'
import type { UploadFileResult } from '@entities/upload-file'
import { uploadFile } from '@features/upload-file/api/uploadFile'

type UploadFileViewState = {
  isLoading: boolean
  error: string | null
  data: UploadFileResult | null
}

const initialState: UploadFileViewState = {
  isLoading: false,
  error: null,
  data: null,
}

export function UploadFileForm() {
  const fileInputRef = useRef<HTMLInputElement | null>(null)
  const [selectedFile, setSelectedFile] = useState<File | null>(null)
  const [state, setState] = useState<UploadFileViewState>(initialState)

  function handleFileChange(event: React.ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0] ?? null

    setSelectedFile(file)
    setState(initialState)
  }

  async function handleMainAction() {
    if (!selectedFile) {
      fileInputRef.current?.click()
      return
    }

    setState({
      isLoading: true,
      error: null,
      data: null,
    })

    try {
      const data = await uploadFile(selectedFile)

      setState({
        isLoading: false,
        error: null,
        data,
      })
    } catch (error) {
      setState({
        isLoading: false,
        error: error instanceof Error ? error.message : 'Unknown upload error',
        data: null,
      })
    }
  }

  return (
    <div className="upload-file-panel">
      <p className="upload-file-panel__description">
        Select a file and send it through the local API Gateway generated by
        floci. The request must reach the upload Lambda and return a 200
        response.
      </p>

      <input
        ref={fileInputRef}
        className="upload-file-panel__native-input"
        type="file"
        onChange={handleFileChange}
      />

      {selectedFile ? (
        <p className="upload-file-panel__selected-file">
          Selected file: {selectedFile.name}
        </p>
      ) : (
        <p className="upload-file-panel__selected-file">
          No file selected yet.
        </p>
      )}

      <button
        className="poc-api-check-button"
        type="button"
        disabled={state.isLoading}
        onClick={handleMainAction}
      >
        {state.isLoading
          ? 'Uploading...'
          : selectedFile
            ? 'Upload file to Lambda'
            : 'Select file'}
      </button>

      {state.error && (
        <div className="upload-file-panel__result upload-file-panel__result--error">
          <p>Error: {state.error}</p>
        </div>
      )}

      {state.data && (
        <div className="upload-file-panel__result">
          <p>HTTP Status: {state.data.httpStatus}</p>
          <p>Lambda Status: {state.data.status}</p>
          <p>Uploaded: {state.data.uploaded ? 'true' : 'false'}</p>
          <p>Service: {state.data.service}</p>
          <p>Message: {state.data.message}</p>
          <p>Filename: {state.data.fileName}</p>
          <p>Content type: {state.data.contentType}</p>
          <p>Parse mode: {state.data.parseMode}</p>
          <p>Size: {state.data.size} bytes</p>
          <p>Timestamp: {state.data.timestamp}</p>
        </div>
      )}
    </div>
  )
}
